services:
    nginx:
      image: nginx:latest
      volumes:
        - ./php:/var/www/html 
        - ./proxy/nginx.conf:/etc/nginx/nginx.conf 
      ports:
        - "8080:80"
      #        - "8043:443"
      depends_on:
        - php
      networks:
        - app-network
      restart: always

    php:  
      build:
        context: ./docker
        dockerfile: Dockerfile.php
      volumes:
        - ./php:/var/www/html
      networks:
        - app-network
      restart: always

    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      restart: always
      ports:
        - "8081:80"
      environment:
        PMA_HOST: db
        PMA_USER: root
        PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      networks:
        - app-network

    db:
      image: mysql:8
      restart: always
      volumes:
        - db:/var/lib/mysql
      networks:
        - app-network
      environment:
        - MYSQL_DATABASE=db
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      ports:
        - "3306:3306"
        - "33060:33060"

networks:
  app-network:
    driver: bridge

volumes:
  db:
